spring.application.name=costurartbaby

spring.profiles.active=test
api.security.token.secret = ${JWT_SECRET:defaultSecret}
yampi.webhook.secret=${YAMPI_WEBHOOK_SECRET:wh_MbqxWGwXovE4XIMe6gVpknatKu20eOpyoPj6p}
yampi.api.token=${YAMPI_TOKEN:your-token}
yampi.api.user-email=${YAMPI_USER_EMAIL:your-email}
yampi.api.url=${YAMPI_URL:https://api.yampi.com.br/v2}